version: '3.8'

services:
  db:
    image: postgres:14.13
    container_name: postgres_db
    environment:
      POSTGRES_USER: hammad
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - '5434:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - mynetwork

volumes:
  db_data:

networks:
  mynetwork:
    driver: bridge
